### ISSUE TITLE
Use GitHub Actions to update/publish website

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi.io#11]
Currently a local `mkdocs` setup is needed. With GitHub Actions publication can be instant on commit.
Will be easy as described in the [Medium.com article](https://medium.com/dev-genius/continuous-deployment-for-mkdocs-with-github-actions-7dceec87f0ea).

**Comment by tomkralidis** [comment]
Thanks for the link @justb4 - super simple to setup!  Implemented in #12.
