### ISSUE TITLE
Internet of Water project info for FOSS4G2021

### ISSUE THREAD

**Issue by ksonda** [geopython/pygeoapi.io#16]
*Internet of Water (Duke University)* 

- geoconnex.us reference feature catalog (https://geoconnex.internetofwater.dev) (with USGS)
  - Persistently identified feature linked-data publication supporting knowledge graph development (https://info.geoconnex.us/collections)
    - US hydrologic features
    - US administrative boundaries
    - US public water systems
    - Surface water monitoring locations

- California multi-agency comprehensive streamgage metadata catalog (with California Water Boards) (https://sb19.linked-data.internetofwater.dev/collections/ca_gages)

- SensorThings API linked data demonstrator 
  - OGC-API Features JSON-LD representation of SensorThings API endpoints (https://pygeoapi-test.info.geoconnex.us/collections) 
  - Demonstration using USGS real-time water measurements STA endpoint (https://labs.waterdata.usgs.gov/sta/v1.1)

@dblodgett-usgs do you want to add the merit stuff

**Comment by tomkralidis** [comment]
@ksonda: summarized/added to https://pygeoapi.io/presentations/foss4g2021/#/5/3.  Let us know if anything needs adjustment.  Thanks again!
