### ISSUE TITLE
failing process execution should return status 500 not 200

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi.io#28]
not sure to report here or on pygeoapi @tomkralidis, this relates to process https://demo.pygeoapi.io/master/processes/pygeometa-metadata-generate/execution

i often get error messages of the process, but they are returned with a status 200, for me it is hard to determine if metadata generation was successfull (and the result is a record) or failed (and the result is a error message)

**Comment by pvgenuchten** [comment]
Ha, this probably relates to https://github.com/geopython/pygeometa/pull/185, so better to log on pygeometa?

**Comment by tomkralidis** [comment]
Closing in lieu of https://github.com/geopython/pygeometa/issues/220

**Comment by tomkralidis** [comment]
> Closing in lieu of [geopython/pygeometa#220](https://github.com/geopython/pygeometa/issues/220)

Sorry, not related to https://github.com/geopython/pygeometa/issues/220

@pvgenuchten can you open a pygeometa issue with a test case to reproduce?  Thanks.
