### ISSUE TITLE
add link to meeting notes of PSC in psc page

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi.io#8]
https://pygeoapi.io/community/psc/ in https://github.com/geopython/pygeoapi.io/blob/master/docs/community/psc.md : add link to meeting notes of PSC in Wiki: https://github.com/geopython/pygeoapi/wiki/Meetings

**Comment by tomkralidis** [comment]
Updated as part of 6776f56317a4e0aad1d97343bd9b12a48a07ff4b .  Let me know if this works.

**Comment by justb4** [comment]
Yes, only minor suggestion is to add to https://github.com/geopython/pygeoapi/wiki/Meetings a (sub) section title  "PSC Meetings" with link to https://pygeoapi.io/community/psc/ just before meeting list, well I could make that change...

**Comment by tomkralidis** [comment]
Done https://pygeoapi.io/community/psc/ let me know if this works.

**Comment by justb4** [comment]
I meant the Wiki page, I edited: https://github.com/geopython/pygeoapi/wiki/Meetings IMO we're done.
